[tool.poetry]
name = "cinema-repertoire-analyzer"
version = "0.1.0"
description = ""
authors = ["Jan Wądołowski <janwadolowski@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
loguru = "^0.5.3"
requests-html = "^0.10.0"
requests = "^2.26.0"
PyYAML = "^6.0"
typer = "^0.4.0"
mypy = "^0.930"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
types-PyYAML = "^6.0.1"
types-requests = "^2.26.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
